### ISSUE TITLE
Weird behavior while Backend is not running.

### ISSUE THREAD

**Issue by LunicLynx** [davidfowl/YarpTunnelDemo#5]
Hey David,

i absolutely love this demo. So first of all thank you very much.

It seems like the url `backend.app` does actually exist. Even though you don't get an result in firefox. 
It resolves to this ip: http://199.241.136.251/

The nginx response confused me like crazy. 

Maybe a 404 or something invalid for the url would be a good idea. It took me quite some time to figure this out and had some major concerns for the integrity of my system 😅 .

Anyway thanks again,
I love the direction asp and .net have taken these past years!

**Comment by davidfowl** [comment]
It's not just me!!!!

**Comment by davidfowl** [comment]
https://github.com/davidfowl/YarpTunnelDemo/commit/c7ae5dd4f32afd52826fe6e00ea4a6b64b96d0c2

**Comment by LunicLynx** [comment]
Thank you. Sorry if I said something wrong.

**Comment by davidfowl** [comment]
No I was trying to track down why this was happening as well.
