### ISSUE TITLE
TunnelConnectionListener fails with OperationCanceledException on .NET 6

### ISSUE THREAD

**Issue by OneCyrus** [davidfowl/YarpTunnelDemo#6]
I tried to downgrade this demo to .NET 6 and it doesn't work as expected. Actually the "backend" project throws a OperationCanceledException in the TunnelConnectionListener at startup. I couldn't find a specific reason why the behavior is different to .NET 7.

any idea?

**Comment by davidfowl** [comment]
Related to https://github.com/davidfowl/YarpTunnelDemo/issues/8

**Comment by davidfowl** [comment]
Fixed in https://github.com/davidfowl/YarpTunnelDemo/commit/6c264d14844b51246d3f6391e22f4eccffa57451
