### ISSUE TITLE
Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by Misiu** [davidfowl/YarpTunnelDemo#8]
I've downloaded the solution files and downgraded all projects to .NET 6.
I had to add:
```
internal sealed class EmptyResult : IResult
{
    internal static readonly EmptyResult Instance = new();

    public Task ExecuteAsync(HttpContext httpContext)
    {
        return Task.CompletedTask;
    }
}
```
and return it instead of `Results.Empty`.

I'm able to run frontend and web application, but when I try to run backend project I get this error:

> System.InvalidOperationException
>   HResult=0x80131509
>   Message=Operation is not valid due to the current state of the object.
>   Source=Microsoft.AspNetCore.Server.Kestrel.Core
>   StackTrace:
>    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.GetDisplayName()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.<BindAsync>d__51.MoveNext()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.<BindAsync>d__2.MoveNext()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<BindAsync>d__33.MoveNext()
>    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__30`1.MoveNext()
>    at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
>    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
>    at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
>    at Program.<Main>$(String[] args) in C:\Users\Tomasz\Downloads\YarpTunnelDemo-main\Backend\Program.cs:line 15

I try to run all 3 projects on the same machine, not sure if this might be the cause.

**Comment by davidfowl** [comment]
.NET 6 doesn't work because we need the ability to write a custom transport and use a custom Endpoint type. I can probably work around it but I haven't tried to as yet.

**Comment by davidfowl** [comment]
Related to https://github.com/davidfowl/YarpTunnelDemo/issues/6

**Comment by davidfowl** [comment]
Fixed in https://github.com/davidfowl/YarpTunnelDemo/commit/6c264d14844b51246d3f6391e22f4eccffa57451
